Issue 4 Deleting an Entry
ameliatalkington/code-journal pull request #8
Opened 2021-02-11 23:29 UTC by ameliatalkington

<img width="1087" alt="Screen Shot 2021-02-11 at 4 16 22 PM" src="https://user-images.githubusercontent.com/52344883/107712194-3bd27d80-6c86-11eb-8f22-4d50d8473747.png">
<img width="1062" alt="Screen Shot 2021-02-11 at 4 16 29 PM" src="https://user-images.githubusercontent.com/52344883/107712198-3e34d780-6c86-11eb-9fef-350a1c9a287f.png">
<img width="266" alt="Screen Shot 2021-02-11 at 4 25 30 PM" src="https://user-images.githubusercontent.com/52344883/107712201-3f660480-6c86-11eb-84d1-23b511ec773b.png">
<img width="256" alt="Screen Shot 2021-02-11 at 4 25 40 PM" src="https://user-images.githubusercontent.com/52344883/107712204-3ffe9b00-6c86-11eb-93c2-147ff97ef1b8.png">

2021-02-11 23:45 UTC, codingcodymiller requested changes
Nice work so far!! Please see my notes

2021-02-11 23:45 UTC, codingcodymiller commented on js/main.js
> +  $delete.className = 'delete invisible';
Why not just use `hidden`?

2021-02-11 23:45 UTC, codingcodymiller commented on js/main.js
> +  $deleteButton.setAttribute('class', 'delete-button');
This does not need to be dynamically created, you can write the delete modal directly in your HTML file, and start it out as hidden.

2021-02-11 23:45 UTC, codingcodymiller commented on css/layout.css
> +
This is likely not necessary, since you already have a `hidden` class

2021-02-12 01:43 UTC, codingcodymiller approved these changes
🥳 🥳 🥳 🥳

2021-02-12 01:46 UTC, ameliatalkington commented
<img width="846" alt="Screen Shot 2021-02-11 at 6 44 20 PM" src="https://user-images.githubusercontent.com/52344883/107721273-80b3df80-6c99-11eb-9616-cfaf6c972fbb.png">

2021-02-12 01:48 UTC, codingcodymiller approved these changes

2021-02-12 01:49 UTC, merged